### ISSUE TITLE
Qt 5.15 and deprecated API

### ISSUE THREAD

**Issue by sashko** [ea4k/klog#466]
Fails to build with Qt 5.15 which is an LTS release due to the deprecated API:

```
../../src/utilities.cpp: In member function ‘bool Utilities::processConfigLine(const QString&)’:
../../src/utilities.cpp:397:53: error: ‘QStringList QString::split(const QString&, QString::SplitBehavior, Qt::CaseSensitivity) const’ is deprecated: Use Qt::SplitBehavior variant instead [-Werror=deprecated-declarations]
  397 |         QStringList values = line.split("=", QT_SKIP);
      |                                                     ^
In file included from ../../../../opt/Qt/5.15.0/gcc_64/include/QtCore/QString:1,
                 from ../../src/utilities.h:37,
                 from ../../src/utilities.cpp:27:
../../../../opt/Qt/5.15.0/gcc_64/include/QtCore/qstring.h:604:17: note: declared here
  604 |     QStringList split(const QString &sep, SplitBehavior behavior,
      |                 ^~~~~
../../src/utilities.cpp: In member function ‘bool Utilities::isValidVUCCGrids(const QString&)’:
../../src/utilities.cpp:1164:34: error: ‘QStringList QString::split(QChar, QString::SplitBehavior, Qt::CaseSensitivity) const’ is deprecated: Use Qt::SplitBehavior variant instead [-Werror=deprecated-declarations]
 1164 |     tmp << _b.split (',', QT_SKIP);
```

If there's no intention to support older Qt versions, I could probably go on and fix it, or perhaps use ifdefs.

**Comment by ikbenkous** [comment]
@sashko `-Werror=deprecated-declarations` is enabled. The compiler treats the deprecation warning as an error and stops compilation.
You can probably disable that flag and have it compile without problems.

I don't know what's smart to do here.
Possible solutions:
1. Disable `-Werror=deprecated-declarations` when using Qt 5.15
2. Not fix it and hope it goes away as Qt 5.15 is used less and less.
3. Use generic C++ string functionality in this case (and possibly more often throughout the project)

@ea4k @ea5wa Can either of you comment on this one?
I don't know about point 3.

I suggest not fixing because Qt 5.15 support is valid until:
`2023-05-26 (Qt Legacy licenses) / 2025-05-26 (Qt Subscription license holders only)`

I do think evaluating whether generic string functionality should be used or not is a smart idea. I don't know personally, since my experience with Qt is a little limited.

**Comment by ea4k** [comment]
Can you explain what do you mean with generic string functionality?
Do you mean for split?

**Comment by ikbenkous** [comment]
I meant: replacing `QString` with `std::string`. This will fix the issue locally but is bound to create issues interfacing with the Qt API. Having thought this over I think it's a bad idea.

Even in this case, a custom `split()` function would be required since `std::string` doesn't have a `split_to_vector()` function unlike Qt... or does it? 🤔

I was trying to think ahead and see if there's ways to future-proof the code and improve quality and prevent issues like this from cropping up in the future. (Hence the core C++ guideline issues!)
Ignore my half-baked ideas if they make no sense. My experience with the code base is limited at best.
